// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'parser.dart';

Future<List<WordTiming>> generateRsvpTimings(
        {required String text,
        required int targetWpm,
        required double paragraphComplexity}) =>
    RustLib.instance.api.crateApiGenerateRsvpTimings(
        text: text,
        targetWpm: targetWpm,
        paragraphComplexity: paragraphComplexity);

Future<List<BionicWord>> generateBionicWords(
        {required String text, required int level}) =>
    RustLib.instance.api.crateApiGenerateBionicWords(text: text, level: level);

Future<(PlatformInt64, double, PlatformInt64)> calculateSm2Review(
        {required int quality,
        required PlatformInt64 currentInterval,
        required double currentEf,
        required PlatformInt64 currentTimeSec}) =>
    RustLib.instance.api.crateApiCalculateSm2Review(
        quality: quality,
        currentInterval: currentInterval,
        currentEf: currentEf,
        currentTimeSec: currentTimeSec);

Future<List<WordTiming>> streamRsvpTimings(
        {required String text,
        required int targetWpm,
        required double paragraphComplexity}) =>
    RustLib.instance.api.crateApiStreamRsvpTimings(
        text: text,
        targetWpm: targetWpm,
        paragraphComplexity: paragraphComplexity);

Future<double> calculateCciScore(
        {required PlatformInt64 avgWpm,
        required double quizAccuracyFraction}) =>
    RustLib.instance.api.crateApiCalculateCciScore(
        avgWpm: avgWpm, quizAccuracyFraction: quizAccuracyFraction);

Future<BigInt> calculateOrpIndex({required String word}) =>
    RustLib.instance.api.crateApiCalculateOrpIndex(word: word);

Future<ParsedDocument> parseFile({required String path}) =>
    RustLib.instance.api.crateApiParseFile(path: path);
