// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'parser.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1698896658;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_core',
    ioDirectory: '../../native/rust_core/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<double> crateApiCalculateCciScore(
      {required PlatformInt64 avgWpm, required double quizAccuracyFraction});

  Future<BigInt> crateApiCalculateOrpIndex({required String word});

  Future<(PlatformInt64, double, PlatformInt64)> crateApiCalculateSm2Review(
      {required int quality,
      required PlatformInt64 currentInterval,
      required double currentEf,
      required PlatformInt64 currentTimeSec});

  Future<List<BionicWord>> crateApiGenerateBionicWords(
      {required String text, required int level});

  Future<List<WordTiming>> crateApiGenerateRsvpTimings(
      {required String text,
      required int targetWpm,
      required double paragraphComplexity});

  Future<ParsedDocument> crateApiParseFile({required String path});

  Future<List<WordTiming>> crateApiStreamRsvpTimings(
      {required String text,
      required int targetWpm,
      required double paragraphComplexity});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<double> crateApiCalculateCciScore(
      {required PlatformInt64 avgWpm, required double quizAccuracyFraction}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_64(avgWpm, serializer);
        sse_encode_f_64(quizAccuracyFraction, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCalculateCciScoreConstMeta,
      argValues: [avgWpm, quizAccuracyFraction],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCalculateCciScoreConstMeta => const TaskConstMeta(
        debugName: "calculate_cci_score",
        argNames: ["avgWpm", "quizAccuracyFraction"],
      );

  @override
  Future<BigInt> crateApiCalculateOrpIndex({required String word}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(word, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_usize,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCalculateOrpIndexConstMeta,
      argValues: [word],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCalculateOrpIndexConstMeta => const TaskConstMeta(
        debugName: "calculate_orp_index",
        argNames: ["word"],
      );

  @override
  Future<(PlatformInt64, double, PlatformInt64)> crateApiCalculateSm2Review(
      {required int quality,
      required PlatformInt64 currentInterval,
      required double currentEf,
      required PlatformInt64 currentTimeSec}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_8(quality, serializer);
        sse_encode_i_64(currentInterval, serializer);
        sse_encode_f_64(currentEf, serializer);
        sse_encode_i_64(currentTimeSec, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_record_i_64_f_64_i_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCalculateSm2ReviewConstMeta,
      argValues: [quality, currentInterval, currentEf, currentTimeSec],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCalculateSm2ReviewConstMeta => const TaskConstMeta(
        debugName: "calculate_sm2_review",
        argNames: ["quality", "currentInterval", "currentEf", "currentTimeSec"],
      );

  @override
  Future<List<BionicWord>> crateApiGenerateBionicWords(
      {required String text, required int level}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(text, serializer);
        sse_encode_u_8(level, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_bionic_word,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGenerateBionicWordsConstMeta,
      argValues: [text, level],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGenerateBionicWordsConstMeta =>
      const TaskConstMeta(
        debugName: "generate_bionic_words",
        argNames: ["text", "level"],
      );

  @override
  Future<List<WordTiming>> crateApiGenerateRsvpTimings(
      {required String text,
      required int targetWpm,
      required double paragraphComplexity}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(text, serializer);
        sse_encode_u_32(targetWpm, serializer);
        sse_encode_f_64(paragraphComplexity, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_word_timing,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiGenerateRsvpTimingsConstMeta,
      argValues: [text, targetWpm, paragraphComplexity],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGenerateRsvpTimingsConstMeta =>
      const TaskConstMeta(
        debugName: "generate_rsvp_timings",
        argNames: ["text", "targetWpm", "paragraphComplexity"],
      );

  @override
  Future<ParsedDocument> crateApiParseFile({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_parsed_document,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiParseFileConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiParseFileConstMeta => const TaskConstMeta(
        debugName: "parse_file",
        argNames: ["path"],
      );

  @override
  Future<List<WordTiming>> crateApiStreamRsvpTimings(
      {required String text,
      required int targetWpm,
      required double paragraphComplexity}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(text, serializer);
        sse_encode_u_32(targetWpm, serializer);
        sse_encode_f_64(paragraphComplexity, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_word_timing,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStreamRsvpTimingsConstMeta,
      argValues: [text, targetWpm, paragraphComplexity],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStreamRsvpTimingsConstMeta => const TaskConstMeta(
        debugName: "stream_rsvp_timings",
        argNames: ["text", "targetWpm", "paragraphComplexity"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BionicWord dco_decode_bionic_word(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BionicWord(
      fullWord: dco_decode_String(arr[0]),
      prefix: dco_decode_String(arr[1]),
      suffix: dco_decode_String(arr[2]),
      boldLength: dco_decode_usize(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BionicWord> dco_decode_list_bionic_word(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bionic_word).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<WordTiming> dco_decode_list_word_timing(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_word_timing).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ParsedDocument dco_decode_parsed_document(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ParsedDocument(
      title: dco_decode_String(arr[0]),
      author: dco_decode_opt_String(arr[1]),
      chunks: dco_decode_list_String(arr[2]),
      wordCount: dco_decode_usize(arr[3]),
      mimeType: dco_decode_String(arr[4]),
    );
  }

  @protected
  (PlatformInt64, double, PlatformInt64) dco_decode_record_i_64_f_64_i_64(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) {
      throw Exception('Expected 3 elements, got ${arr.length}');
    }
    return (
      dco_decode_i_64(arr[0]),
      dco_decode_f_64(arr[1]),
      dco_decode_i_64(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WordTiming dco_decode_word_timing(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return WordTiming(
      word: dco_decode_String(arr[0]),
      delayMs: dco_decode_u_64(arr[1]),
      orpIndex: dco_decode_usize(arr[2]),
      isPunctuationPause: dco_decode_bool(arr[3]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BionicWord sse_decode_bionic_word(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fullWord = sse_decode_String(deserializer);
    var var_prefix = sse_decode_String(deserializer);
    var var_suffix = sse_decode_String(deserializer);
    var var_boldLength = sse_decode_usize(deserializer);
    return BionicWord(
        fullWord: var_fullWord,
        prefix: var_prefix,
        suffix: var_suffix,
        boldLength: var_boldLength);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BionicWord> sse_decode_list_bionic_word(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BionicWord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bionic_word(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<WordTiming> sse_decode_list_word_timing(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WordTiming>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_word_timing(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ParsedDocument sse_decode_parsed_document(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_author = sse_decode_opt_String(deserializer);
    var var_chunks = sse_decode_list_String(deserializer);
    var var_wordCount = sse_decode_usize(deserializer);
    var var_mimeType = sse_decode_String(deserializer);
    return ParsedDocument(
        title: var_title,
        author: var_author,
        chunks: var_chunks,
        wordCount: var_wordCount,
        mimeType: var_mimeType);
  }

  @protected
  (PlatformInt64, double, PlatformInt64) sse_decode_record_i_64_f_64_i_64(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_i_64(deserializer);
    var var_field1 = sse_decode_f_64(deserializer);
    var var_field2 = sse_decode_i_64(deserializer);
    return (var_field0, var_field1, var_field2);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WordTiming sse_decode_word_timing(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_word = sse_decode_String(deserializer);
    var var_delayMs = sse_decode_u_64(deserializer);
    var var_orpIndex = sse_decode_usize(deserializer);
    var var_isPunctuationPause = sse_decode_bool(deserializer);
    return WordTiming(
        word: var_word,
        delayMs: var_delayMs,
        orpIndex: var_orpIndex,
        isPunctuationPause: var_isPunctuationPause);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bionic_word(BionicWord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fullWord, serializer);
    sse_encode_String(self.prefix, serializer);
    sse_encode_String(self.suffix, serializer);
    sse_encode_usize(self.boldLength, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bionic_word(
      List<BionicWord> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bionic_word(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_word_timing(
      List<WordTiming> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_word_timing(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_parsed_document(
      ParsedDocument self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.author, serializer);
    sse_encode_list_String(self.chunks, serializer);
    sse_encode_usize(self.wordCount, serializer);
    sse_encode_String(self.mimeType, serializer);
  }

  @protected
  void sse_encode_record_i_64_f_64_i_64(
      (PlatformInt64, double, PlatformInt64) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.$1, serializer);
    sse_encode_f_64(self.$2, serializer);
    sse_encode_i_64(self.$3, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_word_timing(WordTiming self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.word, serializer);
    sse_encode_u_64(self.delayMs, serializer);
    sse_encode_usize(self.orpIndex, serializer);
    sse_encode_bool(self.isPunctuationPause, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
