// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BionicWord {
  final String fullWord;
  final String prefix;
  final String suffix;
  final BigInt boldLength;

  const BionicWord({
    required this.fullWord,
    required this.prefix,
    required this.suffix,
    required this.boldLength,
  });

  @override
  int get hashCode =>
      fullWord.hashCode ^
      prefix.hashCode ^
      suffix.hashCode ^
      boldLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BionicWord &&
          runtimeType == other.runtimeType &&
          fullWord == other.fullWord &&
          prefix == other.prefix &&
          suffix == other.suffix &&
          boldLength == other.boldLength;
}

class WordTiming {
  final String word;
  final BigInt delayMs;
  final BigInt orpIndex;
  final bool isPunctuationPause;

  const WordTiming({
    required this.word,
    required this.delayMs,
    required this.orpIndex,
    required this.isPunctuationPause,
  });

  @override
  int get hashCode =>
      word.hashCode ^
      delayMs.hashCode ^
      orpIndex.hashCode ^
      isPunctuationPause.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordTiming &&
          runtimeType == other.runtimeType &&
          word == other.word &&
          delayMs == other.delayMs &&
          orpIndex == other.orpIndex &&
          isPunctuationPause == other.isPunctuationPause;
}
