// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ParsedDocument {
  final String title;
  final String? author;
  final List<String> chunks;
  final BigInt wordCount;
  final String mimeType;

  const ParsedDocument({
    required this.title,
    this.author,
    required this.chunks,
    required this.wordCount,
    required this.mimeType,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      author.hashCode ^
      chunks.hashCode ^
      wordCount.hashCode ^
      mimeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParsedDocument &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          author == other.author &&
          chunks == other.chunks &&
          wordCount == other.wordCount &&
          mimeType == other.mimeType;
}
